name: Checkout and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update && \
        sudo apt-get install libunwind-dev \
                             libcurl4-nss-dev \
                             libgstreamer1.0-0 \
                             libgstreamer-plugins-base1.0-dev \
                             gstreamer1.0-plugins-base \
                             gstreamer1.0-plugins-good \
                             gstreamer1.0-plugins-bad \
                             gstreamer1.0-plugins-ugly \
                             gstreamer1.0-libav \
                             gstreamer1.0-tools \
                             gstreamer1.0-x \
                             gstreamer1.0-alsa \
                             gstreamer1.0-gl \
                             gstreamer1.0-gtk3 \
                             gstreamer1.0-pulseaudio \

    - name: Build code
      run: |
        gcc --version
        pkg-config --cflags --libs gstreamer-video-1.0 gstreamer-1.0 libcurl
        gcc ipCamCapture.c ipCamPrinting.c ipCamFTP.c \
            -o ipCamCapture \
            `pkg-config --cflags --libs gstreamer-video-1.0 gstreamer-1.0 libcurl` \
            -D_XOPEN_SOURCE=700 \
            -D_GNU_SOURCE \
            -fcommon
        ls -hal
