name: Checkout and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-nss-dev
        sudo apt-get install libgstreamer1.0-0
        sudo apt-get install gstreamer1.0-plugins-base
        sudo apt-get install gstreamer1.0-plugins-good
        sudo apt-get install gstreamer1.0-plugins-bad
        sudo apt-get install gstreamer1.0-plugins-ugly
        sudo apt-get install gstreamer1.0-libav
        sudo apt-get install gstreamer1.0-tools
        sudo apt-get install gstreamer1.0-x
        sudo apt-get install gstreamer1.0-alsa
        sudo apt-get install gstreamer1.0-gl
        sudo apt-get install gstreamer1.0-gtk3
        sudo apt-get install gstreamer1.0-pulseaudio
        sudo apt-get install libgstreamer-plugins-base1.0-dev
        pkg-config --cflags --libs gstreamer-video-1.0 gstreamer-1.0 libcurl
#        sudo apt-get install gstreamer1.0-doc

    - name: Build code
      run: |
        pwd
        ls -hal
        gcc --version
        gcc ipCamCapture.c ipCamPrinting.c ipCamFTP.c -o ipCamCapture `pkg-config --cflags --libs gstreamer-video-1.0 gstreamer-1.0 libcurl` -D_XOPEN_SOURCE=700 -D_GNU_SOURCE

